// Code generated by 'yaegi extract gameserver/nodes/game/db'. DO NOT EDIT.

//go:build go1.22
// +build go1.22

package symbols

import (
	"gameserver/nodes/game/db"
	"reflect"
)

func init() {
	Symbols["gameserver/nodes/game/db/db"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"CreatePlayer":       reflect.ValueOf(db.CreatePlayer),
		"DotLoginRepository": reflect.ValueOf(&db.DotLoginRepository).Elem(),
		"GetLoginToken":      reflect.ValueOf(db.GetLoginToken),
		"New":                reflect.ValueOf(db.New),
		"PlayerRepository":   reflect.ValueOf(&db.PlayerRepository).Elem(),
		"SetLoginToken":      reflect.ValueOf(db.SetLoginToken),

		// type definitions
		"Component":   reflect.ValueOf((*db.Component)(nil)),
		"DotLogin":    reflect.ValueOf((*db.DotLogin)(nil)),
		"PlayerTable": reflect.ValueOf((*db.PlayerTable)(nil)),
	}
}
