// Code generated by 'yaegi extract gameserver/cherry/extend/string'. DO NOT EDIT.

//go:build go1.22
// +build go1.22

package symbols

import (
	"gameserver/cherry/extend/string"
	"reflect"
)

func init() {
	Symbols["gameserver/cherry/extend/string/cherryString"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"CamelToSnake":  reflect.ValueOf(cherryString.CamelToSnake),
		"CutLastString": reflect.ValueOf(cherryString.CutLastString),
		"IsBlank":       reflect.ValueOf(cherryString.IsBlank),
		"IsNotBlank":    reflect.ValueOf(cherryString.IsNotBlank),
		"SplitIndex":    reflect.ValueOf(cherryString.SplitIndex),
		"ToInt":         reflect.ValueOf(cherryString.ToInt),
		"ToInt32":       reflect.ValueOf(cherryString.ToInt32),
		"ToInt32D":      reflect.ValueOf(cherryString.ToInt32D),
		"ToInt64":       reflect.ValueOf(cherryString.ToInt64),
		"ToInt64D":      reflect.ValueOf(cherryString.ToInt64D),
		"ToIntD":        reflect.ValueOf(cherryString.ToIntD),
		"ToString":      reflect.ValueOf(cherryString.ToString),
		"ToStringSlice": reflect.ValueOf(cherryString.ToStringSlice),
		"ToUint":        reflect.ValueOf(cherryString.ToUint),
		"ToUintD":       reflect.ValueOf(cherryString.ToUintD),
	}
}
