// Code generated by 'yaegi extract gameserver/cherry/components/cron'. DO NOT EDIT.

//go:build go1.22
// +build go1.22

package symbols

import (
	"gameserver/cherry/components/cron"
	"go/constant"
	"go/token"
	"reflect"
)

func init() {
	Symbols["gameserver/cherry/components/cron/cherryCron"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"AddDurationFunc":  reflect.ValueOf(cherryCron.AddDurationFunc),
		"AddEveryDayFunc":  reflect.ValueOf(cherryCron.AddEveryDayFunc),
		"AddEveryHourFunc": reflect.ValueOf(cherryCron.AddEveryHourFunc),
		"AddFunc":          reflect.ValueOf(cherryCron.AddFunc),
		"AddJob":           reflect.ValueOf(cherryCron.AddJob),
		"Entries":          reflect.ValueOf(cherryCron.Entries),
		"Entry":            reflect.ValueOf(cherryCron.Entry),
		"Init":             reflect.ValueOf(cherryCron.Init),
		"Location":         reflect.ValueOf(cherryCron.Location),
		"Name":             reflect.ValueOf(constant.MakeFromLiteral("\"cron_component\"", token.STRING, 0)),
		"New":              reflect.ValueOf(cherryCron.New),
		"Remove":           reflect.ValueOf(cherryCron.Remove),
		"Run":              reflect.ValueOf(cherryCron.Run),
		"Schedule":         reflect.ValueOf(cherryCron.Schedule),
		"Start":            reflect.ValueOf(cherryCron.Start),
		"Stop":             reflect.ValueOf(cherryCron.Stop),

		// type definitions
		"Component":  reflect.ValueOf((*cherryCron.Component)(nil)),
		"CronLogger": reflect.ValueOf((*cherryCron.CronLogger)(nil)),
	}
}
