// Code generated by 'yaegi extract gameserver/nodes/game/module/online'. DO NOT EDIT.

//go:build go1.22
// +build go1.22

package symbols

import (
	"gameserver/nodes/game/module/online"
	"reflect"
)

func init() {
	Symbols["gameserver/nodes/game/module/online/online"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"BindPlayer":   reflect.ValueOf(online.BindPlayer),
		"Count":        reflect.ValueOf(online.Count),
		"UnBindPlayer": reflect.ValueOf(online.UnBindPlayer),
	}
}
