// Code generated by 'yaegi extract gameserver/internal/event'. DO NOT EDIT.

//go:build go1.22
// +build go1.22

package symbols

import (
	"gameserver/internal/event"
	"reflect"
)

func init() {
	Symbols["gameserver/internal/event/event"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"NewPlayerCreate": reflect.ValueOf(event.NewPlayerCreate),
		"NewPlayerLogin":  reflect.ValueOf(event.NewPlayerLogin),
		"NewPlayerLogout": reflect.ValueOf(event.NewPlayerLogout),
		"NoneEventKey":    reflect.ValueOf(&event.NoneEventKey).Elem(),
		"PlayerCreateKey": reflect.ValueOf(&event.PlayerCreateKey).Elem(),
		"PlayerLoginKey":  reflect.ValueOf(&event.PlayerLoginKey).Elem(),
		"PlayerLogoutKey": reflect.ValueOf(&event.PlayerLogoutKey).Elem(),

		// type definitions
		"PlayerCreate": reflect.ValueOf((*event.PlayerCreate)(nil)),
		"PlayerLogin":  reflect.ValueOf((*event.PlayerLogin)(nil)),
		"PlayerLogout": reflect.ValueOf((*event.PlayerLogout)(nil)),
	}
}
