// Code generated by 'yaegi extract gameserver/internal/pb'. DO NOT EDIT.

//go:build go1.22
// +build go1.22

package symbols

import (
	"gameserver/internal/pb"
	"reflect"
)

func init() {
	Symbols["gameserver/internal/pb/pb"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"File_base_error_proto":            reflect.ValueOf(&pb.File_base_error_proto).Elem(),
		"File_base_type_proto":             reflect.ValueOf(&pb.File_base_type_proto).Elem(),
		"File_login_proto":                 reflect.ValueOf(&pb.File_login_proto).Elem(),
		"File_player_proto":                reflect.ValueOf(&pb.File_player_proto).Elem(),
		"File_rpc_proto":                   reflect.ValueOf(&pb.File_rpc_proto).Elem(),
		"NodeState_Closed":                 reflect.ValueOf(pb.NodeState_Closed),
		"NodeState_Maintain":               reflect.ValueOf(pb.NodeState_Maintain),
		"NodeState_Open":                   reflect.ValueOf(pb.NodeState_Open),
		"NodeState_name":                   reflect.ValueOf(&pb.NodeState_name).Elem(),
		"NodeState_value":                  reflect.ValueOf(&pb.NodeState_value).Elem(),
		"PlayerAttribute_AA_AttributeNone": reflect.ValueOf(pb.PlayerAttribute_AA_AttributeNone),
		"PlayerAttribute_name":             reflect.ValueOf(&pb.PlayerAttribute_name).Elem(),
		"PlayerAttribute_value":            reflect.ValueOf(&pb.PlayerAttribute_value).Elem(),

		// type definitions
		"Bool":                 reflect.ValueOf((*pb.Bool)(nil)),
		"DevRegister":          reflect.ValueOf((*pb.DevRegister)(nil)),
		"Double":               reflect.ValueOf((*pb.Double)(nil)),
		"ErrorResponse":        reflect.ValueOf((*pb.ErrorResponse)(nil)),
		"Int32":                reflect.ValueOf((*pb.Int32)(nil)),
		"Int32Int32":           reflect.ValueOf((*pb.Int32Int32)(nil)),
		"Int32Int64":           reflect.ValueOf((*pb.Int32Int64)(nil)),
		"Int32Int64Map":        reflect.ValueOf((*pb.Int32Int64Map)(nil)),
		"Int32List":            reflect.ValueOf((*pb.Int32List)(nil)),
		"Int32Map":             reflect.ValueOf((*pb.Int32Map)(nil)),
		"Int64":                reflect.ValueOf((*pb.Int64)(nil)),
		"Int64Int32":           reflect.ValueOf((*pb.Int64Int32)(nil)),
		"Int64Int64":           reflect.ValueOf((*pb.Int64Int64)(nil)),
		"Int64List":            reflect.ValueOf((*pb.Int64List)(nil)),
		"LoginRequest":         reflect.ValueOf((*pb.LoginRequest)(nil)),
		"LoginResponse":        reflect.ValueOf((*pb.LoginResponse)(nil)),
		"NodeState":            reflect.ValueOf((*pb.NodeState)(nil)),
		"None":                 reflect.ValueOf((*pb.None)(nil)),
		"Player":               reflect.ValueOf((*pb.Player)(nil)),
		"PlayerAttribute":      reflect.ValueOf((*pb.PlayerAttribute)(nil)),
		"PlayerCreateRequest":  reflect.ValueOf((*pb.PlayerCreateRequest)(nil)),
		"PlayerCreateResponse": reflect.ValueOf((*pb.PlayerCreateResponse)(nil)),
		"PlayerEnterResponse":  reflect.ValueOf((*pb.PlayerEnterResponse)(nil)),
		"PlayerSelectResponse": reflect.ValueOf((*pb.PlayerSelectResponse)(nil)),
		"String":               reflect.ValueOf((*pb.String)(nil)),
		"StringKeyValue":       reflect.ValueOf((*pb.StringKeyValue)(nil)),
		"User":                 reflect.ValueOf((*pb.User)(nil)),
	}
}
