// Code generated by 'yaegi extract gameserver/cherry/net/proto'. DO NOT EDIT.

//go:build go1.22
// +build go1.22

package symbols

import (
	"gameserver/cherry/net/proto"
	"reflect"
)

func init() {
	Symbols["gameserver/cherry/net/proto/cherryProto"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"BuildClusterPacket": reflect.ValueOf(cherryProto.BuildClusterPacket),
		"File_proto_proto":   reflect.ValueOf(&cherryProto.File_proto_proto).Elem(),
		"GetClusterPacket":   reflect.ValueOf(cherryProto.GetClusterPacket),

		// type definitions
		"ClusterPacket":       reflect.ValueOf((*cherryProto.ClusterPacket)(nil)),
		"I32":                 reflect.ValueOf((*cherryProto.I32)(nil)),
		"Member":              reflect.ValueOf((*cherryProto.Member)(nil)),
		"MemberList":          reflect.ValueOf((*cherryProto.MemberList)(nil)),
		"PomeloBroadcastPush": reflect.ValueOf((*cherryProto.PomeloBroadcastPush)(nil)),
		"PomeloKick":          reflect.ValueOf((*cherryProto.PomeloKick)(nil)),
		"PomeloPush":          reflect.ValueOf((*cherryProto.PomeloPush)(nil)),
		"PomeloResponse":      reflect.ValueOf((*cherryProto.PomeloResponse)(nil)),
		"Response":            reflect.ValueOf((*cherryProto.Response)(nil)),
		"Session":             reflect.ValueOf((*cherryProto.Session)(nil)),
	}
}
