// Code generated by 'yaegi extract gameserver/internal/data'. DO NOT EDIT.

//go:build go1.22
// +build go1.22

package symbols

import (
	"gameserver/internal/data"
	"reflect"
)

func init() {
	Symbols["gameserver/internal/data/data"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"AreaConfig":       reflect.ValueOf(&data.AreaConfig).Elem(),
		"AreaGroupConfig":  reflect.ValueOf(&data.AreaGroupConfig).Elem(),
		"AreaServerConfig": reflect.ValueOf(&data.AreaServerConfig).Elem(),
		"CodeConfig":       reflect.ValueOf(&data.CodeConfig).Elem(),
		"DecodeData":       reflect.ValueOf(data.DecodeData),
		"New":              reflect.ValueOf(data.New),
		"PlayerInitConfig": reflect.ValueOf(&data.PlayerInitConfig).Elem(),
		"SdkConfig":        reflect.ValueOf(&data.SdkConfig).Elem(),

		// type definitions
		"AreaGroupRow":  reflect.ValueOf((*data.AreaGroupRow)(nil)),
		"AreaRow":       reflect.ValueOf((*data.AreaRow)(nil)),
		"AreaServerRow": reflect.ValueOf((*data.AreaServerRow)(nil)),
		"PlayerInitRow": reflect.ValueOf((*data.PlayerInitRow)(nil)),
		"SdkRow":        reflect.ValueOf((*data.SdkRow)(nil)),
	}
}
