// Code generated by 'yaegi extract gameserver/nodes/game/module/player'. DO NOT EDIT.

//go:build go1.22
// +build go1.22

package symbols

import (
	"gameserver/nodes/game/module/player"
	"reflect"
)

func init() {
	Symbols["gameserver/nodes/game/module/player/player"] = map[string]reflect.Value{
		// type definitions
		"ActorPlayer":  reflect.ValueOf((*player.ActorPlayer)(nil)),
		"ActorPlayers": reflect.ValueOf((*player.ActorPlayers)(nil)),
	}
}
