// Code generated by 'yaegi extract gameserver/hotfix'. DO NOT EDIT.

//go:build go1.22
// +build go1.22

package symbols

import (
	"gameserver/hotfix"
	"reflect"
)

func init() {
	Symbols["gameserver/hotfix/hotfix"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"ApplyFunc": reflect.ValueOf(hotfix.ApplyFunc),

		// type definitions
		"FuncPatch": reflect.ValueOf((*hotfix.FuncPatch)(nil)),
	}
}
