CREATE DATABASE IF NOT EXISTS `dhc_x3_center` CHARACTER SET utf8 COLLATE utf8_general_ci;
CREATE DATABASE IF NOT EXISTS `dhc_x3_game_1` CHARACTER SET utf8 COLLATE utf8_general_ci;
CREATE DATABASE IF NOT EXISTS `dhc_x3_log_1` CHARACTER SET utf8 COLLATE utf8_general_ci;
CREATE DATABASE IF NOT EXISTS `dhc_x3_game_2` CHARACTER SET utf8 COLLATE utf8_general_ci;
CREATE DATABASE IF NOT EXISTS `dhc_x3_log_2` CHARACTER SET utf8 COLLATE utf8_general_ci;